// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWSJz122lpVSAsgUaaOd93XrA3sWXknhs',
    appId: '1:504848877641:web:8f7b281af2499d85e75798',
    messagingSenderId: '504848877641',
    projectId: 'gnos-braille-system',
    authDomain: 'gnos-braille-system.firebaseapp.com',
    storageBucket: 'gnos-braille-system.firebasestorage.app',
    measurementId: 'G-6HP2145FD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSb1typvTNcm33A_i9Y983hekEF86Cr7Q',
    appId: '1:504848877641:android:641db787ef0b0714e75798',
    messagingSenderId: '504848877641',
    projectId: 'gnos-braille-system',
    storageBucket: 'gnos-braille-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAATeAeCmqpdFgypeY97rpC4yRIXSZT3BM',
    appId: '1:504848877641:ios:2c20df866b26f1bbe75798',
    messagingSenderId: '504848877641',
    projectId: 'gnos-braille-system',
    storageBucket: 'gnos-braille-system.firebasestorage.app',
    iosBundleId: 'com.example.gnosBrailleSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAATeAeCmqpdFgypeY97rpC4yRIXSZT3BM',
    appId: '1:504848877641:ios:266d603adf8cbae5e75798',
    messagingSenderId: '504848877641',
    projectId: 'gnos-braille-system',
    storageBucket: 'gnos-braille-system.firebasestorage.app',
    iosBundleId: 'com.example.dotHullAccessibleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWSJz122lpVSAsgUaaOd93XrA3sWXknhs',
    appId: '1:504848877641:web:ce91e4a5f4d6cb08e75798',
    messagingSenderId: '504848877641',
    projectId: 'gnos-braille-system',
    authDomain: 'gnos-braille-system.firebaseapp.com',
    storageBucket: 'gnos-braille-system.firebasestorage.app',
    measurementId: 'G-12QE6Y1EK7',
  );
}
