name: API Deployment

on:
  push:
    branches: [ main ]
    paths: 
      - 'braille_api.py'
      - 'requirements.txt'
      - '.github/workflows/api-deploy.yml'
  release:
    types: [ published ]

jobs:
  test-api:
    name: Test Python API
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Test API
      run: |
        python -m pytest --cov=braille_api --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

  deploy-api-staging:
    name: Deploy API to Staging
    runs-on: ubuntu-latest
    needs: test-api
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to staging server
      run: |
        echo "🚀 Deploying API to staging environment..."
        # Add your staging deployment commands here
        # Example: Deploy to Google Cloud Run, AWS Lambda, etc.
        
  deploy-api-production:
    name: Deploy API to Production
    runs-on: ubuntu-latest
    needs: test-api
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to production server
      run: |
        echo "🚀 Deploying API to production environment..."
        # Add your production deployment commands here
        # Example: Deploy to Google Cloud Run, AWS Lambda, etc.
